main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('timereg.urls')),
    path('admin/', admin.site.urls),
]

timereg/urls.py
from django.urls import path

from . import views

app_name = 'timereg'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event_new, name='event_new'),
    path('event/<int:event_id>/edit/', views.event_edit, name='event_edit'),
]

timereg/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse
from .widget import *


class Event(models.Model):
    title = models.CharField(max_length=200, default="Czas pracy")
    description = models.TextField(blank=True, null=True)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    def timeCout(self):
        time = datetime.combine(datetime(1,1,1,0,0,0), self.end_time) - datetime.combine(datetime(1,1,1,0,0,0), self.start_time)
        return time

    @property
    def get_html_url(self):
        time = self.timeCout()
        url = reverse('timereg:event_edit', args=(self.id,))
        return f'<a href="{url}"> {time} </a>'

    def __str__(self):
        return self.title

timereg/forms.py
from django import forms

from .widget import DatePickerInput, TimePickerInput
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

    date = forms.DateField(
        widget=DatePickerInput
    )

    start_time = forms.TimeField(
        widget=TimePickerInput
    )
    end_time = forms.TimeField(
        widget=TimePickerInput
    )

timereg/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm


class CalendarView(generic.ListView):
    model = Event
    template_name = 'timereg/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # call the formathmonth method, which returtns calendar as a table
        html_cal = cal.formatmonth(withyear=True)

        context = {
            'prev_month': prev_month(d),
            'next_month': next_month(d),
            'calendar': mark_safe(html_cal)
        }   
        return context

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event_new(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('timereg:calendar'))
    context = {
        'form': form
    }
    return render(request, 'timereg/event.html', context)

def event_edit(request, event_id):
    event = Event.objects.get(id=event_id)
    if request.method == 'GET':
        form = EventForm(instance=event)
    else:
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'form': form,
    }
    return render(request, 'timereg/event.html', context)

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .calendar {
            width: 98%;
            margin: auto;
            font-size: 13px;
        }

        .calendar tr, .calendar td {
            border: 1px solid black;
        }

        .calendar th {
            padding: 10px;
            text-align: center;
            font-size: 18px;
        }

        .calendar td {
            width: 200px;
            height: 150px;
            padding: 20px 0 0 5px;
        }

        .month {
            font-size: 25px;
        }

        .date {
            font-size: 25px;
        }

        ul {
            height: 100%;
            padding: 0 5px 0 20px;
        }

        a {
            color: black;
        }

        .left {
            float: left;
        }

        .right {
            float: right;
        }

        .btn {
            outline: none;
            color: black;
            background-color: transparent;
            box-shadow: 0;
        }

        .clearfix {
            margin: 15px;
        }

        .form {
            margin: auto;
        }

        .form input, .form select, .form textarea {
            border-radius: 5px;
            border: 1px solid black;
            outline: none;
            background: none;
            padding: 5px;
            width: 100%;
        }

    </style>

    <title>{% block title %} Base HTML file {% endblock %}</title>
</head>
<body>
    {% include "main/header.html" %}


    {% block content %}
        <h1>Base HTML file</h1>
    {% endblock %}
    
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/main/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        
        <!-- <a class="navbar-brand" href="#">Navbar</a> -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li>
                    <a href="{% url 'timereg:calendar' %}?{{ prev_month }}" class="nav-link"> Previous Month </a>
                </li>
                <li>
                    <a href="{% url 'timereg:calendar' %}?{{ next_month }}" class="nav-link"> Next Month </a>
                </li>
                <li>
                    <a href="{% url 'timereg:event_new' %}" class="nav-link"> New Event </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/timereg/event.html
{% extends "main/base.html" %}

{% block title %} Event {% endblock %}

{% block content %}
<div class="container">
    <br>
    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
            <tr><td colspan="2">
                <button class="btn btn-secondary right" type="submit">Submit</button>
            </td></tr>
        </table>
    </form>
</div>
{% endblock content %}

templates/timereg/event_add.html
{% extends "main/base.html" %}

{% block title %} Event {% endblock %}

{% block content %}
<div class="container">
    <div class="clearfix">
        <a href="{% url 'timereg:calendar' %}" class="btn btn-info left"> Calendar </a>
    </div>

    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
            <tr><td colspan="2">
                <button class="btn btn-info right" type="submit">Submit</button>
            </td></tr>
        </table>
    </form>
</div>
{% endblock content %}

templates/timereg/event_edit.html
{% extends "main/base.html" %}

{% block title %} Edit event {% endblock %}

{% block content %}
<div class="container">
    <br>
    <form method="post">
    {% csrf_token %}
    <table class="form form-table">
        {{ form }}
        <tr><td colspan="2">
            <button class="btn btn-secondary right" type="submit">Submit</button>
        </td></tr>
    </table>
    </form>
</div>
{% endblock content %}

templates/timereg/index.html
{% extends "main/base.html" %}

{% block title %} Work time register app {% endblock %}

{% block content %}
<br>
{{ calendar }}
{% endblock content %}